name: build and push image

on:
  push:
    tags:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag gpoleze/idrive:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: build the image
        run: docker tag gpoleze/idrive gpoleze/idrive:$RELEASE_VERSION
      - name: Push image
        run: docker push gpoleze/idrive:$RELEASE_VERSION